[package]
name = "whos-done-that"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
color-eyre = "0.6.3"
log = "0.4.22"
shell-quote = "0.7.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
